# Generated by Django 6.0.4 on 2026-05-21 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(choices=[('single', 'Single'), ('variable', 'Variable')], default='single', max_length=20)),
                ('product_status', models.CharField(choices=[('pending', 'Pending'), ('publish', 'Publish')], default='pending', max_length=20)),
                ('long_description', models.TextField()),
                ('short_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
