# Generated by Django 6.0.4 on 2026-05-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='describtion',
            new_name='description',
        ),
    ]
