# Generated by Django 6.0.4 on 2026-06-04 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='ecom.subcategory'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
