# Generated by Django 6.0.4 on 2026-06-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_atrribute_productattribute_attributevalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atrribute',
            new_name='Attribute',
        ),
    ]
