# Generated by Django 6.0.4 on 2026-06-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_alter_productattribute_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('tikTok_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('promotion_image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('banner_image_1', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('banner_image_2', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('banner_image_3', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
    ]
