# Generated by Django 6.0.4 on 2026-06-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_generalsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
